version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: calendly-clone-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendly_clone
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:

networks:
  backend:
