import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import Layout, { Content, Footer } from "antd/es/layout/layout";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { Content, Footer } = Layout;
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Layout>
          <AntdRegistry>
            <Content style={{ padding: "0 48px", margin: "40px 0" }}>
              <ConfigProvider wave={{ disabled: true }}>
                {children}
              </ConfigProvider>
            </Content>
            <Footer style={{ textAlign: "center" }}>
              Custom Project ©{new Date().getFullYear()} Created by Mathan
            </Footer>
          </AntdRegistry>
        </Layout>
      </body>
    </html>
  );
}
